### PR TITLE
Svc virt api gateway cfn v330607454

### PR DESCRIPTION
**Pull request by vini-eero**
PR with both CF template and Postman collection that I use in this blog post.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jaymccon** [comment]
@vini-eero apologies for the delay. It looks good, can you just please put the 2 files into a subfolder named with the title of your post. So folder would be something like `blog-assets/my-awesome-post`

**Comment by jaymccon** [comment]
cc @vsnyc for final review/merge

**Review by jaymccon — CHANGES_REQUESTED** [review]
folder structure to be updated

**Comment by vinpereira** [comment]
@jaymccon if required, I could rename the folder.

And thanks for the reply

**Comment by dattasa9** [comment]
Code reviewed and tested for blog, looks okay to proceed.

**Pull request merged**
