### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mobytoby**
Fixed link

*Issue #, if available:*

*Description of changes:*
Replaced placeholder link with the actual link url

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by russomi — APPROVED** [review]
👍 LGTM

**Review by lapkritinis — APPROVED** [review]

**Comment by tobuck-aws** [comment]
I think someone on that side has to merge this PR, right?

**Comment by russomi** [comment]
👋🏼 Hey @tobuck-aws - Merging is blocked until a reviewer of the `aws-quickstart` repo approves the PR and someone who is authorized chooses to merge it.  I expect this would be someone in the aws-quickstart org.

**Review by andrew-glenn — APPROVED** [review]
No idea how this fell under the radar. Thanks for updating this.

**Pull request merged**
